#!/bin/sh
# Keel installer.
#
# Clones the method into ~/.keel and puts a `keel` command on PATH.
#
#   curl -fsSL https://raw.githubusercontent.com/Codcore/keel/main/install.sh | sh
#
# A single file would not be enough: `keel init` copies the references into the
# project beside the tool, so the whole repository has to be somewhere. Cloning
# also makes updating one `git pull`, which is what a second run does.
#
# Override with KEEL_REPO, KEEL_HOME, KEEL_BIN.
set -eu

REPO="${KEEL_REPO:-https://github.com/Codcore/keel.git}"
KEEL_HOME="${KEEL_HOME:-$HOME/.keel}"
KEEL_BIN="${KEEL_BIN:-$HOME/.local/bin}"

for tool in git python3; do
    command -v "$tool" >/dev/null 2>&1 || {
        echo "keel: $tool is required and was not found" >&2
        exit 1
    }
done

if [ -d "$KEEL_HOME/.git" ]; then
    echo "keel: updating $KEEL_HOME"
    git -C "$KEEL_HOME" pull --ff-only --quiet
else
    echo "keel: cloning into $KEEL_HOME"
    git clone --quiet "$REPO" "$KEEL_HOME"
fi

mkdir -p "$KEEL_BIN"
cat > "$KEEL_BIN/keel" <<EOF
#!/bin/sh
# Generated by the Keel installer. Re-run it to update.
exec python3 "$KEEL_HOME/keel.py" "\$@"
EOF
chmod +x "$KEEL_BIN/keel"

version=$(python3 "$KEEL_HOME/keel.py" --version)
echo "keel: $version installed at $KEEL_BIN/keel"

case ":${PATH}:" in
    *":$KEEL_BIN:"*) ;;
    *)
        echo
        echo "$KEEL_BIN is not on your PATH. Add it:"
        echo "  export PATH=\"$KEEL_BIN:\$PATH\""
        ;;
esac

echo
echo "Next, in the project you want to work in:"
echo "  keel init"
